# Generated by Django 6.0 on 2026-01-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="slug",
            field=models.SlugField(default="", null=True),
        ),
    ]
