# Generated by Django 6.0 on 2026-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_member_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
